# Use the existing image as the base image
FROM unityci/editor:windows-2021.3.22f1-windows-il2cpp-2

# Set the UNITY_PATH environment variable
ENV UNITY_PATH="C:\\Program Files\\Unity\\Hub\\Editor\\2021.3.22f1"

# Optional: Set the PATH to include the Unity executable
# ENV PATH="$UNITY_PATH;$PATH"
