# Use the existing image as the base image
FROM unityci/editor:ubuntu-2021.3.22f1-windows-mono-3

# Fixes permission issue https://github.com/game-ci/docker/issues/128
RUN chmod -R 755 /opt/unity/Editor/Data/UnityReferenceAssemblies/



